# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!

target 'Lollie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lollie
  pod 'lottie-ios'
  pod 'Resolver'

  # Pods for Lollie - Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift'

  target 'LollieTests' do
    inherit! :search_paths
    
    # Pods for testing
    pod 'Nimble'
  end

  target 'LollieUITests' do
    # Pods for testing
  end
end
